# Generated by Django 2.1.4 on 2018-12-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='photos'),
        ),
    ]
