# Generated by Django 2.1.3 on 2018-11-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20181130_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
