# Generated by Django 2.1.4 on 2018-12-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20181207_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
