# Generated by Django 2.1.4 on 2018-12-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20181207_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picDate',
        ),
    ]
